import { LazyImage } from "@/components/RandomFox";
import Head from "next/head";
import { useState } from "react";
import type { MouseEventHandler } from "react";

/* 
type ImageItem = Array<{
	id: string;
	url: string;
}>; */

type ImageItem = {
	id: string;
	url: string;
};

export default function Home() {
	const idItem = () => Math.random().toString(36).substring(2, 8);
	const random = () => Math.floor(Math.random() * 123) + 1;

	const [images, setImages] = useState<ImageItem[]>([]);

	const addNexFox: MouseEventHandler<HTMLButtonElement> = (e) => {
		e.preventDefault();
		const newImageItem: ImageItem = {
			id: idItem(),
			url: `https://randomfox.ca/images/${random()}.jpg`,
		};

		setImages([...images, newImageItem]);
	};

	return (
		<>
			{/* 	<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head> */}
			<main>
				<h1 className="bg-slate-900 text-6xl text-white">Sarasa</h1>
				<button onClick={addNexFox}>Add fox 🦊</button>

				{images.map((image) => (
					<div key={image.id} className="p-4">
						<LazyImage
							//img={image.url}
							src={image.url}
							width="320"
							height="auto"
							className="rounded-lg bg-gray-300"
							onClick={() => console.log("cualquiera")}
						/>
					</div>
				))}
			</main>
		</>
	);
}
