import { RandomFox } from "@/components/RandomFox";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
	const random = () => Math.floor(Math.random() * 123) + 1;

	const [images, setImages] = useState<string[]>([
		`https://randomfox.ca/images/${random()}.jpg`,

		`https://randomfox.ca/images/${random()}.jpg`,
		`https://randomfox.ca/images/${random()}.jpg`,
	]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="bg-slate-900 text-6xl text-white">Sarasa</h1>

				{images.map((image, index) => (
					<div key={index} className="p-4">
						<RandomFox img={image} />
					</div>
				))}
			</main>
		</>
	);
}
